export const LISTAR_EVENTOS = 'LISTAR_EVENTOS'
export const CADASTRAR_EVENTO = 'CADASTRAR_EVENTO'
export const EDITAR_EVENTO = 'EDITAR_EVENTO'
export const EXCLUIR_EVENTO = 'EXCLUIR_EVENTO'
export const SALVAR_EVENTO_EDITAR = 'SALVAR_EVENTO_EDITAR'
export const EDITAR_LISTA_2 = 'EDITAR_LISTA_2'

// aux types 
export const TOGGLE_CADASTRAR_MODAL = 'TOGGLE_CADASTRAR_MODAL'
export const TOGGLE_EDITAR_MODAL = 'TOGGLE_EDITAR_MODAL'